# Keeps the commit-pinned GitHub Actions in .github/workflows/ up to date:
# Dependabot opens a pull request when a new release of an action is published.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
